name: Deploy to GOV.UK PaaS

on:
  push:
    branches:
    - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Build docs with middleman
      run: make build

    - name: Configure Cloud Foundry CLI
      uses: DFE-Digital/github-actions/setup-cf-cli@master
      with:
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        CF_SPACE_NAME: technical-architecture

    - name: Push to GOV.UK PaaS
      run: cf push -p build -b staticfile_buildpack --disk 128M --memory 64M dfe-technical-guidance
